players:
  storage: 'yaml'
  # 自动保存。每 60 秒检查队列
  queue-clear-interval: 60
  # 延迟队列，与 queue-clear-interval 选项无关。一段时间大量单次操作则会推迟（一次操作推迟 10 秒），超级大量操作可能推迟很久
  queue-add-time: 10
  yaml:
    # 相对路径 'plugins/Test/a.yml'
    # 绝对路径 'D:/a.yml'
    # 默认路径 ''
    # 迁移路径后数据不会自动迁移，需要手动迁移
    path: ''
  mysql:
    table-prefix: ''
    url: 'jdbc:mysql://localhost:3306/database'      # 数据库的 JDBC URL
    username: 'root'                                 # 数据库用户名
    password: 'password'                             # 数据库密码
    maximum-pool-size: 10                            # 连接池的最大大小，默认建议值 10
    minimum-idle: 10                                 # 连接池中的最小空闲连接数，默认建议与最大连接数相同
    connection-timeout: 30000                        # 获取新连接时的最大等待时间（毫秒），默认建议值 30000
    idle-timeout: 600000                             # 连接空闲的最长时间（毫秒），默认建议值 600000
    maximum-lifetime: 1800000                        # 连接在连接池中存活的最长时间（毫秒），默认建议值 1800000

message:    
  language: 'chinese'
  translations:
    file:
      # 例子 'plugins/Test/翻译'
      # 最终路径 'plugins/Test/翻译/chinese.yml'
      # 迁移路径后数据不会自动迁移，需要手动迁移
      path: ''